### ISSUE TITLE
rel_kpd_handについて

### ISSUE THREAD

**Issue by espelade** [saihyou/nozomi#1]
learn.cpp内のLearner::add_part_param()にてrel_kpd_handは全く触れられていません。ひょっとして漏れではないでしょうか？

**Comment by saihyou** [comment]
ご報告ありがとうございます。
その通りです。
他にも学習コードにはいくつか致命的なバグがありまして。。。
こちらと合わせて、近日中に修正したいと思います。

**Comment by espelade** [comment]
そうでしたか。
修正お待ちしています。
