### ISSUE TITLE
Nozomi x64 binaries are missing (not only for Haswell computers)

### ISSUE THREAD

**Issue by ChessGUI** [saihyou/nozomi#2]
Hello saiyou, can you create Nozomi Windows 64 bit binaries please and host these files on your website ? Is Apery WCSC26 again necessary to run Nozomi x64.exe?

**Comment by saihyou** [comment]
Hi, ChessGUI.

> can you create Nozomi Windows 64 bit binaries please and host these files on your website ?

I have attached nozomi Windows 64 bit binary to release tag.(20160529.zip)
https://github.com/saihyou/nozomi/releases/tag/20160529
nozomi works only on Haswell or later CPU.

> Is Apery WCSC26 again necessary to run Nozomi x64.exe?

No.
