### ISSUE TITLE
PC hardware and software

### ISSUE THREAD

**Issue by ChessGUI** [saihyou/nozomi#3]
Hello saizhyou,
unfortunately I cannot use this executable file on my computer configuration:

Windows 7 SP1 x64
Intel Core i5 3470 @ 3.20GHz Ivy Bridge 22nm Technology
4,00GB RAM Dual-Channel DDR3 @ 798MHz (11-11-11-28)
Motherboard ASRock H61M-DGS R2.0 (CPUSocket)
Instructions    MMX, SSE, SSE2, SSE3, SSSE3, SSE4.1, SSE4.2, Intel 64, NX, VMX, AES, AVX

A Windows binary that  is suitable to my PC system would be better.

**Comment by saihyou** [comment]
Hello ChessGUI,

Sorry, I have no plan to modify for Ivy Bridge CPU at the moment.
